version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    dev-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
