# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  groups:
    dev-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
